USE MASTER
GO
IF exists (SELECT * FROM sysdatabases WHERE name = 'BD3TINDS') 
begin
DROP DATABASE BD3TINDS
Print 'BANCO DROPADO'
end
GO
CREATE DATABASE BD3TINDS
GO
USE BD3TINDS
GO
CREATE TABLE TIPOUSUARIO(
CODTPUSUARIO INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
DESCTPUSUARIO NVARCHAR(60) NOT NULL) 
GO
INSERT INTO TIPOUSUARIO VALUES ('ADMINISTRADOR')
INSERT INTO TIPOUSUARIO VALUES ('USUÁRIO')
GO
CREATE TABLE USUARIO(
CODUSUARIO INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
NOMEUSUARIO NVARCHAR(15) NOT NULL,
SENHAUSUARIO NVARCHAR(15) NOT NULL,
CODTPUSUARIO INT NOT NULL,
FOREIGN KEY (CODTPUSUARIO) REFERENCES  TIPOUSUARIO (CODTPUSUARIO))
GO
INSERT INTO USUARIO VALUES ('ADM','ADM', 1)
INSERT INTO USUARIO VALUES ('USR','USR', 2)
GO
SELECT * FROM TIPOUSUARIO
SELECT * FROM USUARIO